---

- name: Install MySQL
  yum: name={{ item }}
  with_items:
    - MySQL-python
    - mariadb
    - mariadb-server

- name: Start the MySQL service
  service: name=mariadb state=started enabled=yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host="{{ item }}" password={{ mysql_root_password }}
  ignore_errors: true
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: delete anonymous MySQL server user for $server_hostname
  mysql_user: user="" host={{ item }} state="absent"
  with_items:
    - "{{ inventory_hostname }}"
    - "%"

- name: delete anonymous MySQL server user for localhost
  mysql_user: user=""  state="absent"

- name: remove the MySQL test database
  mysql_db: db=test state=absent

- name: Add multicraft databases
  mysql_db: name={{ item }} state=present
  with_items:
    - multicraft_panel
    - multicraft_demon

- name: Add multicraft users
  mysql_user: user={{ item }} password={{ demon_pass }} state="present" host="%" priv={{ item }}.*:ALL
  with_items:
    - multicraft_panel
    - multicraft_demon

- name: Add bind address to /etc/my.cnf
  template: src=my.cnf dest=/etc/my.cnf
  notify:
    - restart mysqld
